### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by damwhit** [Aeickelman40/mod_0_skills#1]
@Aeickelman40 great job on this! You are officially `technical ready`! Great attention to detail with your syntax and style. A couple of things that stuck out and I think could help you be even more clear in the future:
* the attribute`passHealthInspection` reads more like a method to me because it is in present tense. What might be a better name?
* the `newUniforms` method reads more like an attribute to me. What would make it more clear that it's a method?
Excellent work on this. These were the only two areas where I think changing some naming could make things even more readable.

**Comment by Aeickelman40** [comment]
@damwhit awesome, thanks for the good news! Thank you for the feedback as well, I tried to triple check everything prior to submitting just to make sure I had everything in proper order. 

* Instead of `passHealthInspection`, `healthCertificate` would be more appropriate as an attribute because it sounds like less of a command. 

* The `updateUniforms` method could be a replacement as it is a verb instead of a noun. 

Let me know what you think of these, happy holidays!
